/** Declaration file generated by dts-gen */

export = vorpal;

declare class vorpal {
    constructor();

    CmdHistoryExtension(): void;

    catch(name: any, desc: any, opts: any): any;

    command(name: any, desc: any, opts: any): any;

    default(name: any, desc: any, opts: any): any;

    delimiter(str: any): any;

    exec(cmd: any, args: any, cb: any): any;

    execSync(cmd: any, options: any): any;

    exit(options: any): void;

    find(name: any): any;

    getSessionById(id: any): any;

    help(fn: any): void;

    hide(): any;

    history(id: any): any;

    historyStoragePath(path: any): any;

    hook(fn: any): any;

    localStorage(id: any): any;

    log(...args: any[]): any;

    mode(name: any, desc: any, opts: any): any;

    parse(argv: any, options: any): any;

    pipe(fn: any): any;

    prompt(...args: any[]): any;

    show(): any;

    sigint(fn: any): any;

    use(commands: any, options: any): any;

    version(version: any): any;

}

